name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install build twine

      - run: python -m build

      - run: twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
